spring.datasource.url=jdbc:h2:mem:paymentdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

external.api.url=http://localhost:8081


resilience4j.retry.instances.exchangeRateApi.max-attempts=3
resilience4j.retry.instances.exchangeRateApi.wait-duration=500ms
resilience4j.retry.instances.exchangeRateApi.retry-exceptions=feign.FeignException$ServiceUnavailable,feign.FeignException$GatewayTimeout

resilience4j.circuitbreaker.instances.exchangeRateApi.sliding-window-size=10
resilience4j.circuitbreaker.instances.exchangeRateApi.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.exchangeRateApi.wait-duration-in-open-state=10s

resilience4j.timelimiter.instances.exchangeRateApi.timeout-duration=2s


logging.level.root=INFO
logging.level.com.example.globalpayment=DEBUG
logging.level.com.example.globalpayment.clients.ExchangeRateClient=DEBUG